exclude:
  - Dockerfile
  - Makefile
  - load_repo_info.py
  - resume
  - poetry.lock
  - pyproject.toml
  - requirements.txt
  - deploy.sh

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

navigation:
  - url: /Vlad-Polietaiev-Resume.pdf
    label: Resume
  - url: https://github.com/poletaevvlad
    label: GitHub

contacts:
  - url: mailto:poletaev.vladislav@gmail.com
    label: poletaev.vladislav@gmail.com
  - url: https://github.com/poletaevvlad
    label: poletaevvlad
    prefix: "GitHub:"
