exclude:
  - Dockerfile
  - Makefile
  - load_repo_info.py
  - resume

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

navigation:
  - url: https://github.com/poletaevvlad
    label: GitHub

contacts:
  - url: mailto:poletaev.vladislav@gmail.com
    label: poletaev.vladislav@gmail.com
  - url: https://github.com/poletaevvlad
    label: poletaevvlad
    prefix: "GitHub:"
